---
title: "day 9"
author: "Jake Eisaguirre"
date: "8/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
library(tidyverse)
library(palmerpenguins)
library(lubridate)
library(janitor)
library(reprex)
```

### Janitor::get_dupes()
```{r}

starwars_dupes <- get_dupes(starwars)

starwars_dupes_names <- starwars %>% 
  get_dupes(hair_color)

starwars_dupes_hc_ec <- starwars %>% 
  get_dupes(hair_color, eye_color)

```

### dplyr::across()

```{r}

sw_across <- starwars %>% 
  
  mutate(across(where(is.character), tolower))

sw_across

```
find the mean of all 
```{r}

starwars %>% 
  
  group_by(homeworld) %>% 
  
  summarize(across(where(is.numeric), mean, na.rm = T))


```
### basic / common trouble shooting
```{r}

starwars %>% 
  
  filter(homeworld == "Naboo") # double equal not single equal

```

```{r}

starwars %>% 
  
  separate(skin_color, into = c("col_1", "col_2"), sep = ",") ## use sep not by

```

```{r}

ggplot(mtcars, aes(x = wt, y = mpg)) + ## use plus not pipe operator 
  geom_point()

```

```{r}

peng <- penguins %>% 
  
  mutate(across(where(is.numeric), as.character)) %>% 
  
  mutate(island = fct_relevel(island, c("Dream",
                                        "Biscoe",
                                        "Torgersen"))) %>% 
  
  unite(island_yr, c(island, year), sep = "_") %>% 
  
  filter(species %in% c("Adelie", "Chinstrap")) %>% 
  
  relocate(island_yr, .after = species) %>% 
  
  rename(penguin_spp = species)

```



```{r}

library(tidyverse)

df <- tribble(
  
  ~name, ~height, ~hair_color,
  "Teddy", 2.2, "brown",
  "Khora", 1.0, "white",
  "Waffle", 1.0, "tan",
)

df %>% 
  filter(name == "Waffle")

```








